# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 537cf250173dcec0d6de3470188f67e986a12eb824e6d3f46d76bc2540088aae7f57b7cedf447e7bd9f5b5e888b1fed9fe3b78eb96821bddff3b0cd24bf5b4ac

test:
  secret_key_base: d7ffe10699453517531595fa64db967ec234b15da6e58e8d4c7f690bafe756f0b2b6f9ad1de81ea7b54ac651a711899e273b5b8dfde78138268151718c0cba50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
